- name: Remove hostname from /etc/hosts
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1|::1)[ \t]+{{ ipa.hostname }}.*$'
    state: absent

- name: Install IPA server
  become: True
  shell: |
    /usr/sbin/ipa-server-install --unattended          \
      --realm={{ ipa.domain | upper | quote }}         \
      --domain={{ ipa.domain | quote }}                \
      --ds-password={{ ipa.password | quote }}         \
      --admin-password={{ ipa.password | quote }}      \
      --hostname={{ ipa.fqn | quote }}                 \
      --setup-dns                                      \
      --auto-forwarders                                \
      --auto-reverse                                   \
      --no-dnssec-validation                           \
      --no-host-dns
  register: ipa_installation
  args:
    creates: /etc/ipa/default.conf

- name: Remove vagrant IP addresses from /etc/hosts because they can change over time
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(?!{{ ipa.ip }}).*master.ipa.vm master$'
    state: absent
  register: etc_hosts

- name: Create /etc/NetworkManager/conf.d/disable_dns.conf
  become: True
  template:
    src: disable_dns.conf
    dest: /etc/NetworkManager/conf.d/disable_dns.conf
    owner: root
    group: root
    mode: 0644
  register: nm_conf

- name: Restart NetworkManager
  become: True
  service:
    name: NetworkManager.service
    enabled: yes
    state: restarted
  when: etc_hosts.changed or nm_conf.changed
