- name: 'Remove vagrant IP address from DNS'
  win_shell: |
    Remove-DnsServerResourceRecord \
      -ZoneName "{{ item.zone }}"  \
      -RRType "A"                  \
      -Name "{{ item.name }}"      \
      -RecordData "{{ item.ip }}"  \
      -Force
  when: inventory_hostname == 'ad'
  register: dns
  failed_when: dns.rc != 0 and dns.stderr is not search('ObjectNotFound')
  changed_when: dns.rc == 0
  with_items:
    - { zone: '{{ domain }}', name: '{{ hostname }}', ip: '{{ ansible_ip_addresses[0] }}' }
    - { zone: '{{ domain }}', name: '{{ domain }}.', ip: '{{ ansible_ip_addresses[0] }}' }
